<?php

use Illuminate\Database\Seeder;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Kota::create(['kota' => 'Kabupaten Aceh Barat','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Aceh Barat Daya','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Aceh Besar','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Aceh Jaya','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Aceh Selatan','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Aceh Singkil','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Aceh Tamiang','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Aceh Tengah','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Aceh Tenggara','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Aceh Timur','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Aceh Utara','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Agam','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Alor','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kota Ambon','propinsi_id' => 19]);
        \App\Kota::create(['kota' => 'Kabupaten Asahan','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Asmat','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Badung','propinsi_id' => 1]);
        \App\Kota::create(['kota' => 'Kabupaten Balangan','propinsi_id' => 13]);
        \App\Kota::create(['kota' => 'Kota Balikpapan','propinsi_id' => 15]);
        \App\Kota::create(['kota' => 'Kota Banda Aceh','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kota Bandar Lampung','propinsi_id' => 18]);
        \App\Kota::create(['kota' => 'Kabupaten Bandung','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kota Bandung','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Bandung Barat','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Banggai','propinsi_id' => 29]);
        \App\Kota::create(['kota' => 'Kabupaten Banggai Kepulauan','propinsi_id' => 29]);
        \App\Kota::create(['kota' => 'Kabupaten Bangka','propinsi_id' => 2]);
        \App\Kota::create(['kota' => 'Kabupaten Bangka Barat','propinsi_id' => 2]);
        \App\Kota::create(['kota' => 'Kabupaten Bangka Selatan','propinsi_id' => 2]);
        \App\Kota::create(['kota' => 'Kabupaten Bangka Tengah','propinsi_id' => 2]);
        \App\Kota::create(['kota' => 'Kabupaten Bangkalan','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Bangli','propinsi_id' => 1]);
        \App\Kota::create(['kota' => 'Kabupaten Banjar','propinsi_id' => 13]);
        \App\Kota::create(['kota' => 'Kota Banjar','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kota Banjarbaru','propinsi_id' => 13]);
        \App\Kota::create(['kota' => 'Kota Banjarmasin','propinsi_id' => 13]);
        \App\Kota::create(['kota' => 'Kabupaten Banjarnegara','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Bantaeng','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Bantul','propinsi_id' => 5]);
        \App\Kota::create(['kota' => 'Kabupaten Banyuasin','propinsi_id' => 33]);
        \App\Kota::create(['kota' => 'Kabupaten Banyumas','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Banyuwangi','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Barito Kuala','propinsi_id' => 13]);
        \App\Kota::create(['kota' => 'Kabupaten Barito Selatan','propinsi_id' => 14]);
        \App\Kota::create(['kota' => 'Kabupaten Barito Timur','propinsi_id' => 14]);
        \App\Kota::create(['kota' => 'Kabupaten Barito Utara','propinsi_id' => 14]);
        \App\Kota::create(['kota' => 'Kabupaten Barru','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kota Batam','propinsi_id' => 17]);
        \App\Kota::create(['kota' => 'Kabupaten Batang','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Batang Hari','propinsi_id' => 8]);
        \App\Kota::create(['kota' => 'Kota Batu','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Batu Bara','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kota Bau-Bau','propinsi_id' => 30]);
        \App\Kota::create(['kota' => 'Kabupaten Bekasi','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kota Bekasi','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Belitung','propinsi_id' => 2]);
        \App\Kota::create(['kota' => 'Kabupaten Belitung Timur','propinsi_id' => 2]);
        \App\Kota::create(['kota' => 'Kabupaten Belu','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kabupaten Bener Meriah','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Bengkalis','propinsi_id' => 26]);
        \App\Kota::create(['kota' => 'Kabupaten Bengkayang','propinsi_id' => 12]);
        \App\Kota::create(['kota' => 'Kota Bengkulu','propinsi_id' => 4]);
        \App\Kota::create(['kota' => 'Kabupaten Bengkulu Selatan','propinsi_id' => 4]);
        \App\Kota::create(['kota' => 'Kabupaten Bengkulu Tengah','propinsi_id' => 4]);
        \App\Kota::create(['kota' => 'Kabupaten Bengkulu Utara','propinsi_id' => 4]);
        \App\Kota::create(['kota' => 'Kabupaten Berau','propinsi_id' => 15]);
        \App\Kota::create(['kota' => 'Kabupaten Biak Numfor','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Bima','propinsi_id' => 22]);
        \App\Kota::create(['kota' => 'Kota Bima','propinsi_id' => 22]);
        \App\Kota::create(['kota' => 'Kota Binjai','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Bintan','propinsi_id' => 17]);
        \App\Kota::create(['kota' => 'Kabupaten Bireuen','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kota Bitung','propinsi_id' => 31]);
        \App\Kota::create(['kota' => 'Kabupaten Blitar','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kota Blitar','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Blora','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Boalemo','propinsi_id' => 7]);
        \App\Kota::create(['kota' => 'Kabupaten Bogor','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kota Bogor','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Bojonegoro','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Bolaang Mongondow (Bolmong)','propinsi_id' => 31]);
        \App\Kota::create(['kota' => 'Kabupaten Bolaang Mongondow Selatan','propinsi_id' => 31]);
        \App\Kota::create(['kota' => 'Kabupaten Bolaang Mongondow Timur','propinsi_id' => 31]);
        \App\Kota::create(['kota' => 'Kabupaten Bolaang Mongondow Utara','propinsi_id' => 31]);
        \App\Kota::create(['kota' => 'Kabupaten Bombana','propinsi_id' => 30]);
        \App\Kota::create(['kota' => 'Kabupaten Bondowoso','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Bone','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Bone Bolango','propinsi_id' => 7]);
        \App\Kota::create(['kota' => 'Kota Bontang','propinsi_id' => 15]);
        \App\Kota::create(['kota' => 'Kabupaten Boven Digoel','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Boyolali','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Brebes','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kota Bukittinggi','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Buleleng','propinsi_id' => 1]);
        \App\Kota::create(['kota' => 'Kabupaten Bulukumba','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Bulungan (Bulongan)','propinsi_id' => 16]);
        \App\Kota::create(['kota' => 'Kabupaten Bungo','propinsi_id' => 8]);
        \App\Kota::create(['kota' => 'Kabupaten Buol','propinsi_id' => 29]);
        \App\Kota::create(['kota' => 'Kabupaten Buru','propinsi_id' => 19]);
        \App\Kota::create(['kota' => 'Kabupaten Buru Selatan','propinsi_id' => 19]);
        \App\Kota::create(['kota' => 'Kabupaten Buton','propinsi_id' => 30]);
        \App\Kota::create(['kota' => 'Kabupaten Buton Utara','propinsi_id' => 30]);
        \App\Kota::create(['kota' => 'Kabupaten Ciamis','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Cianjur','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Cilacap','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kota Cilegon','propinsi_id' => 3]);
        \App\Kota::create(['kota' => 'Kota Cimahi','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Cirebon','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kota Cirebon','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Dairi','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Deiyai (Deliyai)','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Deli Serdang','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Demak','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kota Denpasar','propinsi_id' => 1]);
        \App\Kota::create(['kota' => 'Kota Depok','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Dharmasraya','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Dogiyai','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Dompu','propinsi_id' => 22]);
        \App\Kota::create(['kota' => 'Kabupaten Donggala','propinsi_id' => 29]);
        \App\Kota::create(['kota' => 'Kota Dumai','propinsi_id' => 26]);
        \App\Kota::create(['kota' => 'Kabupaten Empat Lawang','propinsi_id' => 33]);
        \App\Kota::create(['kota' => 'Kabupaten Ende','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kabupaten Enrekang','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Fakfak','propinsi_id' => 25]);
        \App\Kota::create(['kota' => 'Kabupaten Flores Timur','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kabupaten Garut','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Gayo Lues','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Gianyar','propinsi_id' => 1]);
        \App\Kota::create(['kota' => 'Kabupaten Gorontalo','propinsi_id' => 7]);
        \App\Kota::create(['kota' => 'Kota Gorontalo','propinsi_id' => 7]);
        \App\Kota::create(['kota' => 'Kabupaten Gorontalo Utara','propinsi_id' => 7]);
        \App\Kota::create(['kota' => 'Kabupaten Gowa','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Gresik','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Grobogan','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Gunung Kidul','propinsi_id' => 5]);
        \App\Kota::create(['kota' => 'Kabupaten Gunung Mas','propinsi_id' => 14]);
        \App\Kota::create(['kota' => 'Kota Gunungsitoli','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Halmahera Barat','propinsi_id' => 20]);
        \App\Kota::create(['kota' => 'Kabupaten Halmahera Selatan','propinsi_id' => 20]);
        \App\Kota::create(['kota' => 'Kabupaten Halmahera Tengah','propinsi_id' => 20]);
        \App\Kota::create(['kota' => 'Kabupaten Halmahera Timur','propinsi_id' => 20]);
        \App\Kota::create(['kota' => 'Kabupaten Halmahera Utara','propinsi_id' => 20]);
        \App\Kota::create(['kota' => 'Kabupaten Hulu Sungai Selatan','propinsi_id' => 13]);
        \App\Kota::create(['kota' => 'Kabupaten Hulu Sungai Tengah','propinsi_id' => 13]);
        \App\Kota::create(['kota' => 'Kabupaten Hulu Sungai Utara','propinsi_id' => 13]);
        \App\Kota::create(['kota' => 'Kabupaten Humbang Hasundutan','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Indragiri Hilir','propinsi_id' => 26]);
        \App\Kota::create(['kota' => 'Kabupaten Indragiri Hulu','propinsi_id' => 26]);
        \App\Kota::create(['kota' => 'Kabupaten Indramayu','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Intan Jaya','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kota Jakarta Barat','propinsi_id' => 6]);
        \App\Kota::create(['kota' => 'Kota Jakarta Pusat','propinsi_id' => 6]);
        \App\Kota::create(['kota' => 'Kota Jakarta Selatan','propinsi_id' => 6]);
        \App\Kota::create(['kota' => 'Kota Jakarta Timur','propinsi_id' => 6]);
        \App\Kota::create(['kota' => 'Kota Jakarta Utara','propinsi_id' => 6]);
        \App\Kota::create(['kota' => 'Kota Jambi','propinsi_id' => 8]);
        \App\Kota::create(['kota' => 'Kabupaten Jayapura','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kota Jayapura','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Jayawijaya','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Jember','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Jembrana','propinsi_id' => 1]);
        \App\Kota::create(['kota' => 'Kabupaten Jeneponto','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Jepara','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Jombang','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Kaimana','propinsi_id' => 25]);
        \App\Kota::create(['kota' => 'Kabupaten Kampar','propinsi_id' => 26]);
        \App\Kota::create(['kota' => 'Kabupaten Kapuas','propinsi_id' => 14]);
        \App\Kota::create(['kota' => 'Kabupaten Kapuas Hulu','propinsi_id' => 12]);
        \App\Kota::create(['kota' => 'Kabupaten Karanganyar','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Karangasem','propinsi_id' => 1]);
        \App\Kota::create(['kota' => 'Kabupaten Karawang','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Karimun','propinsi_id' => 17]);
        \App\Kota::create(['kota' => 'Kabupaten Karo','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Katingan','propinsi_id' => 14]);
        \App\Kota::create(['kota' => 'Kabupaten Kaur','propinsi_id' => 4]);
        \App\Kota::create(['kota' => 'Kabupaten Kayong Utara','propinsi_id' => 12]);
        \App\Kota::create(['kota' => 'Kabupaten Kebumen','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Kediri','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kota Kediri','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Keerom','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Kendal','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kota Kendari','propinsi_id' => 30]);
        \App\Kota::create(['kota' => 'Kabupaten Kepahiang','propinsi_id' => 4]);
        \App\Kota::create(['kota' => 'Kabupaten Kepulauan Anambas','propinsi_id' => 17]);
        \App\Kota::create(['kota' => 'Kabupaten Kepulauan Aru','propinsi_id' => 19]);
        \App\Kota::create(['kota' => 'Kabupaten Kepulauan Mentawai','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Kepulauan Meranti','propinsi_id' => 26]);
        \App\Kota::create(['kota' => 'Kabupaten Kepulauan Sangihe','propinsi_id' => 31]);
        \App\Kota::create(['kota' => 'Kabupaten Kepulauan Seribu','propinsi_id' => 6]);
        \App\Kota::create(['kota' => 'Kabupaten Kepulauan Siau Tagulandang Biaro (Sitaro)','propinsi_id' => 31]);
        \App\Kota::create(['kota' => 'Kabupaten Kepulauan Sula','propinsi_id' => 20]);
        \App\Kota::create(['kota' => 'Kabupaten Kepulauan Talaud','propinsi_id' => 31]);
        \App\Kota::create(['kota' => 'Kabupaten Kepulauan Yapen (Yapen Waropen)','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Kerinci','propinsi_id' => 8]);
        \App\Kota::create(['kota' => 'Kabupaten Ketapang','propinsi_id' => 12]);
        \App\Kota::create(['kota' => 'Kabupaten Klaten','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Klungkung','propinsi_id' => 1]);
        \App\Kota::create(['kota' => 'Kabupaten Kolaka','propinsi_id' => 30]);
        \App\Kota::create(['kota' => 'Kabupaten Kolaka Utara','propinsi_id' => 30]);
        \App\Kota::create(['kota' => 'Kabupaten Konawe','propinsi_id' => 30]);
        \App\Kota::create(['kota' => 'Kabupaten Konawe Selatan','propinsi_id' => 30]);
        \App\Kota::create(['kota' => 'Kabupaten Konawe Utara','propinsi_id' => 30]);
        \App\Kota::create(['kota' => 'Kabupaten Kotabaru','propinsi_id' => 13]);
        \App\Kota::create(['kota' => 'Kota Kotamobagu','propinsi_id' => 31]);
        \App\Kota::create(['kota' => 'Kabupaten Kotawaringin Barat','propinsi_id' => 14]);
        \App\Kota::create(['kota' => 'Kabupaten Kotawaringin Timur','propinsi_id' => 14]);
        \App\Kota::create(['kota' => 'Kabupaten Kuantan Singingi','propinsi_id' => 26]);
        \App\Kota::create(['kota' => 'Kabupaten Kubu Raya','propinsi_id' => 12]);
        \App\Kota::create(['kota' => 'Kabupaten Kudus','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Kulon Progo','propinsi_id' => 5]);
        \App\Kota::create(['kota' => 'Kabupaten Kuningan','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Kupang','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kota Kupang','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kabupaten Kutai Barat','propinsi_id' => 15]);
        \App\Kota::create(['kota' => 'Kabupaten Kutai Kartanegara','propinsi_id' => 15]);
        \App\Kota::create(['kota' => 'Kabupaten Kutai Timur','propinsi_id' => 15]);
        \App\Kota::create(['kota' => 'Kabupaten Labuhan Batu','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Labuhan Batu Selatan','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Labuhan Batu Utara','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Lahat','propinsi_id' => 33]);
        \App\Kota::create(['kota' => 'Kabupaten Lamandau','propinsi_id' => 14]);
        \App\Kota::create(['kota' => 'Kabupaten Lamongan','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Lampung Barat','propinsi_id' => 18]);
        \App\Kota::create(['kota' => 'Kabupaten Lampung Selatan','propinsi_id' => 18]);
        \App\Kota::create(['kota' => 'Kabupaten Lampung Tengah','propinsi_id' => 18]);
        \App\Kota::create(['kota' => 'Kabupaten Lampung Timur','propinsi_id' => 18]);
        \App\Kota::create(['kota' => 'Kabupaten Lampung Utara','propinsi_id' => 18]);
        \App\Kota::create(['kota' => 'Kabupaten Landak','propinsi_id' => 12]);
        \App\Kota::create(['kota' => 'Kabupaten Langkat','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kota Langsa','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Lanny Jaya','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Lebak','propinsi_id' => 3]);
        \App\Kota::create(['kota' => 'Kabupaten Lebong','propinsi_id' => 4]);
        \App\Kota::create(['kota' => 'Kabupaten Lembata','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kota Lhokseumawe','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Lima Puluh Koto\/Kota','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Lingga','propinsi_id' => 17]);
        \App\Kota::create(['kota' => 'Kabupaten Lombok Barat','propinsi_id' => 22]);
        \App\Kota::create(['kota' => 'Kabupaten Lombok Tengah','propinsi_id' => 22]);
        \App\Kota::create(['kota' => 'Kabupaten Lombok Timur','propinsi_id' => 22]);
        \App\Kota::create(['kota' => 'Kabupaten Lombok Utara','propinsi_id' => 22]);
        \App\Kota::create(['kota' => 'Kota Lubuk Linggau','propinsi_id' => 33]);
        \App\Kota::create(['kota' => 'Kabupaten Lumajang','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Luwu','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Luwu Timur','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Luwu Utara','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Madiun','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kota Madiun','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Magelang','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kota Magelang','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Magetan','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Majalengka','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Majene','propinsi_id' => 27]);
        \App\Kota::create(['kota' => 'Kota Makassar','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Malang','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kota Malang','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Malinau','propinsi_id' => 16]);
        \App\Kota::create(['kota' => 'Kabupaten Maluku Barat Daya','propinsi_id' => 19]);
        \App\Kota::create(['kota' => 'Kabupaten Maluku Tengah','propinsi_id' => 19]);
        \App\Kota::create(['kota' => 'Kabupaten Maluku Tenggara','propinsi_id' => 19]);
        \App\Kota::create(['kota' => 'Kabupaten Maluku Tenggara Barat','propinsi_id' => 19]);
        \App\Kota::create(['kota' => 'Kabupaten Mamasa','propinsi_id' => 27]);
        \App\Kota::create(['kota' => 'Kabupaten Mamberamo Raya','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Mamberamo Tengah','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Mamuju','propinsi_id' => 27]);
        \App\Kota::create(['kota' => 'Kabupaten Mamuju Utara','propinsi_id' => 27]);
        \App\Kota::create(['kota' => 'Kota Manado','propinsi_id' => 31]);
        \App\Kota::create(['kota' => 'Kabupaten Mandailing Natal','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Manggarai','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kabupaten Manggarai Barat','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kabupaten Manggarai Timur','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kabupaten Manokwari','propinsi_id' => 25]);
        \App\Kota::create(['kota' => 'Kabupaten Manokwari Selatan','propinsi_id' => 25]);
        \App\Kota::create(['kota' => 'Kabupaten Mappi','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Maros','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kota Mataram','propinsi_id' => 22]);
        \App\Kota::create(['kota' => 'Kabupaten Maybrat','propinsi_id' => 25]);
        \App\Kota::create(['kota' => 'Kota Medan','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Melawi','propinsi_id' => 12]);
        \App\Kota::create(['kota' => 'Kabupaten Merangin','propinsi_id' => 8]);
        \App\Kota::create(['kota' => 'Kabupaten Merauke','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Mesuji','propinsi_id' => 18]);
        \App\Kota::create(['kota' => 'Kota Metro','propinsi_id' => 18]);
        \App\Kota::create(['kota' => 'Kabupaten Mimika','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Minahasa','propinsi_id' => 31]);
        \App\Kota::create(['kota' => 'Kabupaten Minahasa Selatan','propinsi_id' => 31]);
        \App\Kota::create(['kota' => 'Kabupaten Minahasa Tenggara','propinsi_id' => 31]);
        \App\Kota::create(['kota' => 'Kabupaten Minahasa Utara','propinsi_id' => 31]);
        \App\Kota::create(['kota' => 'Kabupaten Mojokerto','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kota Mojokerto','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Morowali','propinsi_id' => 29]);
        \App\Kota::create(['kota' => 'Kabupaten Muara Enim','propinsi_id' => 33]);
        \App\Kota::create(['kota' => 'Kabupaten Muaro Jambi','propinsi_id' => 8]);
        \App\Kota::create(['kota' => 'Kabupaten Muko Muko','propinsi_id' => 4]);
        \App\Kota::create(['kota' => 'Kabupaten Muna','propinsi_id' => 30]);
        \App\Kota::create(['kota' => 'Kabupaten Murung Raya','propinsi_id' => 14]);
        \App\Kota::create(['kota' => 'Kabupaten Musi Banyuasin','propinsi_id' => 33]);
        \App\Kota::create(['kota' => 'Kabupaten Musi Rawas','propinsi_id' => 33]);
        \App\Kota::create(['kota' => 'Kabupaten Nabire','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Nagan Raya','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Nagekeo','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kabupaten Natuna','propinsi_id' => 17]);
        \App\Kota::create(['kota' => 'Kabupaten Nduga','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Ngada','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kabupaten Nganjuk','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Ngawi','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Nias','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Nias Barat','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Nias Selatan','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Nias Utara','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Nunukan','propinsi_id' => 16]);
        \App\Kota::create(['kota' => 'Kabupaten Ogan Ilir','propinsi_id' => 33]);
        \App\Kota::create(['kota' => 'Kabupaten Ogan Komering Ilir','propinsi_id' => 33]);
        \App\Kota::create(['kota' => 'Kabupaten Ogan Komering Ulu','propinsi_id' => 33]);
        \App\Kota::create(['kota' => 'Kabupaten Ogan Komering Ulu Selatan','propinsi_id' => 33]);
        \App\Kota::create(['kota' => 'Kabupaten Ogan Komering Ulu Timur','propinsi_id' => 33]);
        \App\Kota::create(['kota' => 'Kabupaten Pacitan','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kota Padang','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Padang Lawas','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Padang Lawas Utara','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kota Padang Panjang','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Padang Pariaman','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kota Padang Sidempuan','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kota Pagar Alam','propinsi_id' => 33]);
        \App\Kota::create(['kota' => 'Kabupaten Pakpak Bharat','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kota Palangka Raya','propinsi_id' => 14]);
        \App\Kota::create(['kota' => 'Kota Palembang','propinsi_id' => 33]);
        \App\Kota::create(['kota' => 'Kota Palopo','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kota Palu','propinsi_id' => 29]);
        \App\Kota::create(['kota' => 'Kabupaten Pamekasan','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Pandeglang','propinsi_id' => 3]);
        \App\Kota::create(['kota' => 'Kabupaten Pangandaran','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Pangkajene Kepulauan','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kota Pangkal Pinang','propinsi_id' => 2]);
        \App\Kota::create(['kota' => 'Kabupaten Paniai','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kota Parepare','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kota Pariaman','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Parigi Moutong','propinsi_id' => 29]);
        \App\Kota::create(['kota' => 'Kabupaten Pasaman','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Pasaman Barat','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Paser','propinsi_id' => 15]);
        \App\Kota::create(['kota' => 'Kabupaten Pasuruan','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kota Pasuruan','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Pati','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kota Payakumbuh','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Pegunungan Arfak','propinsi_id' => 25]);
        \App\Kota::create(['kota' => 'Kabupaten Pegunungan Bintang','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Pekalongan','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kota Pekalongan','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kota Pekanbaru','propinsi_id' => 26]);
        \App\Kota::create(['kota' => 'Kabupaten Pelalawan','propinsi_id' => 26]);
        \App\Kota::create(['kota' => 'Kabupaten Pemalang','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kota Pematang Siantar','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Penajam Paser Utara','propinsi_id' => 15]);
        \App\Kota::create(['kota' => 'Kabupaten Pesawaran','propinsi_id' => 18]);
        \App\Kota::create(['kota' => 'Kabupaten Pesisir Barat','propinsi_id' => 18]);
        \App\Kota::create(['kota' => 'Kabupaten Pesisir Selatan','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Pidie','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Pidie Jaya','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Pinrang','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Pohuwato','propinsi_id' => 7]);
        \App\Kota::create(['kota' => 'Kabupaten Polewali Mandar','propinsi_id' => 27]);
        \App\Kota::create(['kota' => 'Kabupaten Ponorogo','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Pontianak','propinsi_id' => 12]);
        \App\Kota::create(['kota' => 'Kota Pontianak','propinsi_id' => 12]);
        \App\Kota::create(['kota' => 'Kabupaten Poso','propinsi_id' => 29]);
        \App\Kota::create(['kota' => 'Kota Prabumulih','propinsi_id' => 33]);
        \App\Kota::create(['kota' => 'Kabupaten Pringsewu','propinsi_id' => 18]);
        \App\Kota::create(['kota' => 'Kabupaten Probolinggo','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kota Probolinggo','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Pulang Pisau','propinsi_id' => 14]);
        \App\Kota::create(['kota' => 'Kabupaten Pulau Morotai','propinsi_id' => 20]);
        \App\Kota::create(['kota' => 'Kabupaten Puncak','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Puncak Jaya','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Purbalingga','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Purwakarta','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Purworejo','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Raja Ampat','propinsi_id' => 25]);
        \App\Kota::create(['kota' => 'Kabupaten Rejang Lebong','propinsi_id' => 4]);
        \App\Kota::create(['kota' => 'Kabupaten Rembang','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Rokan Hilir','propinsi_id' => 26]);
        \App\Kota::create(['kota' => 'Kabupaten Rokan Hulu','propinsi_id' => 26]);
        \App\Kota::create(['kota' => 'Kabupaten Rote Ndao','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kota Sabang','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Sabu Raijua','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kota Salatiga','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kota Samarinda','propinsi_id' => 15]);
        \App\Kota::create(['kota' => 'Kabupaten Sambas','propinsi_id' => 12]);
        \App\Kota::create(['kota' => 'Kabupaten Samosir','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Sampang','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Sanggau','propinsi_id' => 12]);
        \App\Kota::create(['kota' => 'Kabupaten Sarmi','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Sarolangun','propinsi_id' => 8]);
        \App\Kota::create(['kota' => 'Kota Sawah Lunto','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Sekadau','propinsi_id' => 12]);
        \App\Kota::create(['kota' => 'Kabupaten Selayar (Kepulauan Selayar)','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Seluma','propinsi_id' => 4]);
        \App\Kota::create(['kota' => 'Kabupaten Semarang','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kota Semarang','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Seram Bagian Barat','propinsi_id' => 19]);
        \App\Kota::create(['kota' => 'Kabupaten Seram Bagian Timur','propinsi_id' => 19]);
        \App\Kota::create(['kota' => 'Kabupaten Serang','propinsi_id' => 3]);
        \App\Kota::create(['kota' => 'Kota Serang','propinsi_id' => 3]);
        \App\Kota::create(['kota' => 'Kabupaten Serdang Bedagai','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Seruyan','propinsi_id' => 14]);
        \App\Kota::create(['kota' => 'Kabupaten Siak','propinsi_id' => 26]);
        \App\Kota::create(['kota' => 'Kota Sibolga','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Sidenreng Rappang\/Rapang','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Sidoarjo','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Sigi','propinsi_id' => 29]);
        \App\Kota::create(['kota' => 'Kabupaten Sijunjung (Sawah Lunto Sijunjung)','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Sikka','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kabupaten Simalungun','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Simeulue','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kota Singkawang','propinsi_id' => 12]);
        \App\Kota::create(['kota' => 'Kabupaten Sinjai','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Sintang','propinsi_id' => 12]);
        \App\Kota::create(['kota' => 'Kabupaten Situbondo','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Sleman','propinsi_id' => 5]);
        \App\Kota::create(['kota' => 'Kabupaten Solok','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kota Solok','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Solok Selatan','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Soppeng','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Sorong','propinsi_id' => 25]);
        \App\Kota::create(['kota' => 'Kota Sorong','propinsi_id' => 25]);
        \App\Kota::create(['kota' => 'Kabupaten Sorong Selatan','propinsi_id' => 25]);
        \App\Kota::create(['kota' => 'Kabupaten Sragen','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Subang','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kota Subulussalam','propinsi_id' => 21]);
        \App\Kota::create(['kota' => 'Kabupaten Sukabumi','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kota Sukabumi','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Sukamara','propinsi_id' => 14]);
        \App\Kota::create(['kota' => 'Kabupaten Sukoharjo','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Sumba Barat','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kabupaten Sumba Barat Daya','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kabupaten Sumba Tengah','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kabupaten Sumba Timur','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kabupaten Sumbawa','propinsi_id' => 22]);
        \App\Kota::create(['kota' => 'Kabupaten Sumbawa Barat','propinsi_id' => 22]);
        \App\Kota::create(['kota' => 'Kabupaten Sumedang','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kabupaten Sumenep','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kota Sungaipenuh','propinsi_id' => 8]);
        \App\Kota::create(['kota' => 'Kabupaten Supiori','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kota Surabaya','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kota Surakarta (Solo)','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Tabalong','propinsi_id' => 13]);
        \App\Kota::create(['kota' => 'Kabupaten Tabanan','propinsi_id' => 1]);
        \App\Kota::create(['kota' => 'Kabupaten Takalar','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Tambrauw','propinsi_id' => 25]);
        \App\Kota::create(['kota' => 'Kabupaten Tana Tidung','propinsi_id' => 16]);
        \App\Kota::create(['kota' => 'Kabupaten Tana Toraja','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Tanah Bumbu','propinsi_id' => 13]);
        \App\Kota::create(['kota' => 'Kabupaten Tanah Datar','propinsi_id' => 32]);
        \App\Kota::create(['kota' => 'Kabupaten Tanah Laut','propinsi_id' => 13]);
        \App\Kota::create(['kota' => 'Kabupaten Tangerang','propinsi_id' => 3]);
        \App\Kota::create(['kota' => 'Kota Tangerang','propinsi_id' => 3]);
        \App\Kota::create(['kota' => 'Kota Tangerang Selatan','propinsi_id' => 3]);
        \App\Kota::create(['kota' => 'Kabupaten Tanggamus','propinsi_id' => 18]);
        \App\Kota::create(['kota' => 'Kota Tanjung Balai','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Tanjung Jabung Barat','propinsi_id' => 8]);
        \App\Kota::create(['kota' => 'Kabupaten Tanjung Jabung Timur','propinsi_id' => 8]);
        \App\Kota::create(['kota' => 'Kota Tanjung Pinang','propinsi_id' => 17]);
        \App\Kota::create(['kota' => 'Kabupaten Tapanuli Selatan','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Tapanuli Tengah','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Tapanuli Utara','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Tapin','propinsi_id' => 13]);
        \App\Kota::create(['kota' => 'Kota Tarakan','propinsi_id' => 16]);
        \App\Kota::create(['kota' => 'Kabupaten Tasikmalaya','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kota Tasikmalaya','propinsi_id' => 9]);
        \App\Kota::create(['kota' => 'Kota Tebing Tinggi','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Tebo','propinsi_id' => 8]);
        \App\Kota::create(['kota' => 'Kabupaten Tegal','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kota Tegal','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Teluk Bintuni','propinsi_id' => 25]);
        \App\Kota::create(['kota' => 'Kabupaten Teluk Wondama','propinsi_id' => 25]);
        \App\Kota::create(['kota' => 'Kabupaten Temanggung','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kota Ternate','propinsi_id' => 20]);
        \App\Kota::create(['kota' => 'Kota Tidore Kepulauan','propinsi_id' => 20]);
        \App\Kota::create(['kota' => 'Kabupaten Timor Tengah Selatan','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kabupaten Timor Tengah Utara','propinsi_id' => 23]);
        \App\Kota::create(['kota' => 'Kabupaten Toba Samosir','propinsi_id' => 34]);
        \App\Kota::create(['kota' => 'Kabupaten Tojo Una-Una','propinsi_id' => 29]);
        \App\Kota::create(['kota' => 'Kabupaten Toli-Toli','propinsi_id' => 29]);
        \App\Kota::create(['kota' => 'Kabupaten Tolikara','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kota Tomohon','propinsi_id' => 31]);
        \App\Kota::create(['kota' => 'Kabupaten Toraja Utara','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Trenggalek','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kota Tual','propinsi_id' => 19]);
        \App\Kota::create(['kota' => 'Kabupaten Tuban','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Tulang Bawang','propinsi_id' => 18]);
        \App\Kota::create(['kota' => 'Kabupaten Tulang Bawang Barat','propinsi_id' => 18]);
        \App\Kota::create(['kota' => 'Kabupaten Tulungagung','propinsi_id' => 11]);
        \App\Kota::create(['kota' => 'Kabupaten Wajo','propinsi_id' => 28]);
        \App\Kota::create(['kota' => 'Kabupaten Wakatobi','propinsi_id' => 30]);
        \App\Kota::create(['kota' => 'Kabupaten Waropen','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Way Kanan','propinsi_id' => 18]);
        \App\Kota::create(['kota' => 'Kabupaten Wonogiri','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Wonosobo','propinsi_id' => 10]);
        \App\Kota::create(['kota' => 'Kabupaten Yahukimo','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kabupaten Yalimo','propinsi_id' => 24]);
        \App\Kota::create(['kota' => 'Kota Yogyakarta','propinsi_id' => 5]);	
    }
}
